'use client';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type Self = { id: string; name: string; origin: string | null; startDate: string | null; endDate: string | null; budget: number | null; destinationType: string | null; excludedDestinations: string[]; preferences: string; dealbreakers: string; submitted: boolean };
type Position = { memberId: string; name: string; cost: number | null; budget: number; score: number; position: string };
type Quote = { currency: string; quotedAt: string; hotelName: string; hotelTotal: number; flightPrices: Record<string, number>; flightLinks: Record<string, string>; hotelLink: string };
type Option = { id: string; city: string; country: string; iata: string; destination_type: string; reason: string; score: number; total_cost: number; quote: Quote; positions: Position[] };
type Trip = { title: string; currency: string; organizer: boolean; self: Self | null; members: { name: string; submitted: boolean }[]; round: { id: string; status: string; issues: string[]; stale: boolean; locked_option_id: string | null; created_at: string; options: Option[]; tally: Record<string, number>; myVote: string | null } | null; previousRounds: { id: string; status: string; createdAt: string }[] };

export default function TripPage() {
  const { slug } = useParams<{ slug: string }>();
  const [secret, setSecret] = useState('');
  const [trip, setTrip] = useState<Trip | null>(null);
  const [name, setName] = useState('');
  const [form, setForm] = useState({ origin: '', startDate: '', endDate: '', budget: '', destinationType: 'any', excludedDestinations: '', preferences: '', dealbreakers: '' });
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [lockOption, setLockOption] = useState('');
  const load = useCallback(async (key: string) => {
    try {
      const response = await fetch(`/api/trips/${slug}`, { headers: key ? { 'x-member-token': key } : {}, cache: 'no-store' });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      setTrip(data);
      if (data.self) setForm({ origin: data.self.origin || '', startDate: data.self.startDate || '', endDate: data.self.endDate || '', budget: String(data.self.budget || ''), destinationType: data.self.destinationType || 'any', excludedDestinations: (data.self.excludedDestinations || []).join(', '), preferences: data.self.preferences || '', dealbreakers: data.self.dealbreakers || '' });
      setLockOption(data.round?.locked_option_id || data.round?.options?.[0]?.id || '');
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load trip.'); }
  }, [slug]);
  useEffect(() => { const match = location.hash.match(/^#(?:member|organizer)=([A-Za-z0-9_-]+)$/); const key = match?.[1] || ''; setSecret(key); void load(key); }, [load]);
  async function act(action: string, payload: Record<string, unknown> = {}) {
    setBusy(action); setError(''); setNotice('');
    try {
      const response = await fetch(`/api/trips/${slug}`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(secret ? { 'x-member-token': secret } : {}) }, body: JSON.stringify({ action, ...payload }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      if (data.token) { location.hash = `member=${data.token}`; setSecret(data.token); await load(data.token); }
      else { await load(secret); setNotice(action === 'submit' ? 'Preferences saved. Keep your private link to edit them later.' : action === 'vote' ? 'Your vote is saved. You can change it until the result is locked.' : action === 'lock' ? 'The group choice is locked.' : action === 'generate' ? 'The new round is ready.' : 'Saved.'); }
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Something went wrong. Try again.'); }
    finally { setBusy(''); }
  }
  async function copy(value: string, label: string) { await navigator.clipboard.writeText(value); setNotice(`${label} copied.`); }
  const sharedLink = typeof window === 'undefined' ? '' : `${location.origin}/trip/${slug}`;
  const privateLink = typeof window === 'undefined' ? '' : `${location.origin}/trip/${slug}#${trip?.organizer ? 'organizer' : 'member'}=${secret}`;
  const submitted = trip?.members.filter(m => m.submitted).length || 0;
  return <main className="site-shell trip-shell"><header className="topbar"><a className="wordmark" href="/">gather<span>.</span></a><span className="eyebrow">THE GROUP TRIP STUDIO</span></header>
    {!trip ? <section className="loading">{error || 'Opening your trip…'}</section> : <><div className="trip-heading"><div><div className="index-label"><span className="dot"/> YOUR GROUP SPACE</div><h1>{trip.title}</h1><p>The trip takes shape as everyone adds their piece.</p></div><div className="share-box"><span>GROUP INVITE LINK</span><code>{sharedLink}</code><button onClick={() => copy(sharedLink, 'Group link')}>Copy link ↗</button></div></div>
    <div className="trip-grid"><div className="main-column"><section className="panel progress-panel"><div className="section-heading"><div><span className="section-index">01 / THE PEOPLE</span><h2>Everyone in?</h2></div><strong>{submitted}<small> / {trip.members.length} ready</small></strong></div><div className="progress-bar"><span style={{ width: `${trip.members.length ? submitted / trip.members.length * 100 : 0}%` }}/></div><div className="people-list">{trip.members.map((m, i) => <div className="person" key={`${m.name}-${i}`}><span className="avatar">{m.name.slice(0, 1).toUpperCase()}</span><span>{m.name}{trip.self?.name === m.name ? <em> · you</em> : ''}</span><span className={m.submitted ? 'status done' : 'status'}>{m.submitted ? 'READY' : 'WAITING'}</span></div>)}</div></section>
      {!trip.self && <section className="panel"><span className="section-index">JOIN THE GROUP</span><h2>Pull up a seat.</h2><p>Anyone with the group link can join. Your answer gets its own private edit link.</p><form onSubmit={e => { e.preventDefault(); void act('join', { name }); }} className="inline-form"><input value={name} maxLength={50} onChange={e => setName(e.target.value)} placeholder="Your name" required/><button className="primary" disabled={!!busy}>Join trip ↗</button></form></section>}
      {trip.self && <section className="panel"><div className="section-heading"><div><span className="section-index">02 / YOUR PREFERENCES</span><h2>{trip.self.submitted ? 'Your plans, your call.' : 'Tell us what works.'}</h2></div><span className="quiet-tag">PRIVATE TO YOUR LINK</span></div><p>Use an airport code for your origin. Dates and budget are firm limits when we check options.</p><form onSubmit={e => { e.preventDefault(); void act('submit', form); }} className="preference-form"><div className="form-row"><label>ORIGIN AIRPORT CODE<input required maxLength={3} placeholder="DEL" value={form.origin} onChange={e => setForm({ ...form, origin: e.target.value.toUpperCase() })}/></label><label>BUDGET PER PERSON · {trip.currency}<input required type="number" min="1" placeholder="1200" value={form.budget} onChange={e => setForm({ ...form, budget: e.target.value })}/></label></div><div className="form-row"><label>EARLIEST DEPARTURE<input required type="date" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })}/></label><label>LATEST RETURN<input required type="date" value={form.endDate} onChange={e => setForm({ ...form, endDate: e.target.value })}/></label></div><label>DESTINATION STYLE<select value={form.destinationType} onChange={e => setForm({ ...form, destinationType: e.target.value })}><option value="any">Open to anything</option><option value="beach">Beach</option><option value="city">City</option><option value="nature">Nature</option><option value="adventure">Adventure</option><option value="culture">Culture</option></select></label><label>EXCLUDED DESTINATIONS <small>comma separated, strictly enforced</small><input placeholder="Goa, Thailand" value={form.excludedDestinations} onChange={e => setForm({ ...form, excludedDestinations: e.target.value })}/></label><label>WHAT WOULD MAKE THIS GREAT?<textarea rows={3} placeholder="Food, quiet mornings, hiking..." value={form.preferences} onChange={e => setForm({ ...form, preferences: e.target.value })}/></label><label>OTHER DEALBREAKERS <small>shared with the recommendation model</small><textarea rows={2} placeholder="No overnight layovers..." value={form.dealbreakers} onChange={e => setForm({ ...form, dealbreakers: e.target.value })}/></label><button disabled={!!busy} className="primary">{busy === 'submit' ? 'Saving…' : trip.self.submitted ? 'Save changes ↗' : 'Submit preferences ↗'}</button></form><div className="private-link"><div><strong>Your private edit link</strong><p>Keep this link. Anyone with it can edit your answers and vote as you.</p></div><button onClick={() => copy(privateLink, 'Private link')}>Copy private link ↗</button></div></section>}
      <section className="panel results-panel"><div className="section-heading"><div><span className="section-index">03 / THE OPTIONS</span><h2>Find your common ground.</h2></div>{trip.round && <span className="quiet-tag">ROUND · {new Date(trip.round.created_at).toLocaleDateString()}</span>}</div>
        {!trip.round && <p>{submitted === trip.members.length && trip.members.length >= 2 ? 'Everyone is ready. The organiser can generate options now.' : 'Options appear once at least two people have joined and everyone has submitted.'}</p>}
        {trip.round?.stale && <p className="notice">Preferences changed or someone joined since this round. The organiser can start a fresh round; this result stays in the history.</p>}
        {trip.round?.status === 'conflict' && <div className="conflict"><strong>No verified option this round</strong><p>Here is what stopped a recommendation:</p><ul>{trip.round.issues.map((issue, i) => <li key={i}>{issue}</li>)}</ul></div>}
        {trip.round?.options.map((option, index) => <article className={`option ${trip.round?.locked_option_id === option.id ? 'chosen' : ''}`} key={option.id}><div className="option-top"><span>OPTION {String(index + 1).padStart(2, '0')} · {option.destination_type.toUpperCase()}</span><span>{option.score}% GROUP FIT</span></div><h3>{option.city}<small>, {option.country}</small></h3><p>{option.reason}</p><div className="option-prices"><div><span>GROUP ESTIMATE</span><strong>{trip.currency} {Math.round(option.total_cost).toLocaleString()}</strong></div><div><span>HOTEL</span><strong>{option.quote.hotelName}</strong></div></div><div className="positions">{option.positions.map(position => <div key={position.memberId}><span>{position.name}</span><span>{position.position}</span><strong>{position.cost === null ? 'Unavailable' : `${trip.currency} ${position.cost.toLocaleString()}`} <small>/ {position.budget.toLocaleString()} budget</small></strong></div>)}</div><div className="option-actions"><span>{trip.round?.locked_option_id === option.id ? '✓ CHOSEN TRIP' : `${trip.round?.tally[option.id] || 0} vote${trip.round?.tally[option.id] === 1 ? '' : 's'}`}</span>{trip.self && trip.round?.status === 'ready' && <button onClick={() => act('vote', { optionId: option.id })} disabled={!!busy || trip.round?.stale}>{trip.round?.myVote === option.id ? 'Your vote ✓' : 'Vote for this ↗'}</button>}</div><div className="quote-foot">Live Amadeus quote · {new Date(option.quote.quotedAt).toLocaleString()} · Availability and prices can change. <a href={option.quote.hotelLink} target="_blank" rel="noreferrer">Compare hotels ↗</a>{trip.self && option.quote.flightLinks[trip.self.id] && <> · <a href={option.quote.flightLinks[trip.self.id]} target="_blank" rel="noreferrer">Compare flights ↗</a></>}</div></article>)}
        {trip.round?.status === 'ready' && trip.organizer && <div className="lock-row"><select aria-label="Option to lock" value={lockOption} onChange={e => setLockOption(e.target.value)}>{trip.round.options.map(option => <option key={option.id} value={option.id}>{option.city} · {trip.round?.tally[option.id] || 0} votes</option>)}</select><button className="primary" disabled={!!busy || !lockOption || trip.round.stale} onClick={() => act('lock', { optionId: lockOption })}>Lock group choice ↗</button></div>}
        <p className="coverage">Flight coverage is limited by Amadeus inventory. Quotes are estimates, and booking searches may show different prices. Only options with live flight and hotel offers are shown. Review free-text dealbreakers together before booking.</p>
      </section></div>
    <aside className="side-column"><section className="aside-card"><span className="section-index">YOUR NEXT STEP</span><h2>{!trip.self ? 'Join the trip.' : !trip.self.submitted ? 'Add your preferences.' : submitted < trip.members.length ? 'Invite the rest.' : trip.round?.status === 'ready' && !trip.round.myVote ? 'Cast your vote.' : trip.round?.status === 'locked' ? 'Trip decided.' : 'Ready for options.'}</h2><p>{!trip.self ? 'Enter your name in the group space.' : !trip.self.submitted ? 'A few details make the options useful for everyone.' : submitted < trip.members.length ? 'Share the group link with anyone still missing.' : trip.round?.status === 'locked' ? 'The organiser has locked the group choice.' : 'Every response is in. The organiser can start a round.'}</p>{trip.organizer && submitted === trip.members.length && trip.members.length >= 2 && <button className="secondary" disabled={!!busy} onClick={() => act('generate')}>{busy === 'generate' ? 'Checking live offers…' : trip.round ? 'Start new round ↗' : 'Generate options ↗'}</button>}</section><section className="aside-note"><span>HOW IT WORKS</span><p>We check shared dates, every budget and excluded destinations against live flight and hotel offers before showing a fit.</p></section>{trip.previousRounds.length > 0 && <section className="aside-note"><span>EARLIER ROUNDS</span>{trip.previousRounds.map(round => <p key={round.id}>{new Date(round.createdAt).toLocaleDateString()} · {round.status}</p>)}</section>}</aside></div>
    {(error || notice) && <div className={error ? 'toast error' : 'toast'} role="status">{error || notice}<button onClick={() => { setError(''); setNotice(''); }} aria-label="Dismiss">×</button></div>}
    </>}
    <footer className="footer"><span>GOOD PLANS MAKE ROOM FOR EVERYONE.</span><span>GATHER · GROUP TRAVEL</span></footer></main>;
}
